<?php

return [
    'visa' => [
        'badge_en' => 'Fast-Track Worldwide Visas',
        'badge_ar' => 'خدمات التأشيرات المعتمدة',
        'heading_en' => 'Fast-Track Global',
        'heading_ar' => 'استخراج التأشيرات لجميع',
        'highlight_en' => 'Visa Assistance',
        'highlight_ar' => 'دول العالم',
        'description_en' => 'End-to-end visa assistance for Saudi citizens & residents. Appointment booking, official translations, and application filing.',
        'description_ar' => 'فريق متخصص لمساعدتك في استخراج تأشيرات الشنغن، بريطانيا، وأمريكا مع حجز المواعيد وتعبئة النماذج وتجهيز ملفك كاملاً.',
        'tabs' => [
            ['id' => 'all', 'label_en' => 'All Destinations', 'label_ar' => 'جميع التأشيرات'],
            ['id' => 'europe', 'label_en' => '🇪🇺 Europe & UK', 'label_ar' => '🇪🇺 أوروبا وبريطانيا'],
            ['id' => 'americas', 'label_en' => '🇺🇸 USA & Canada', 'label_ar' => '🇺🇸 أمريكا وكندا'],
            ['id' => 'asia', 'label_en' => '🇯🇵 Asia', 'label_ar' => '🇯🇵 آسيا وشرق آسيا'],
        ],
        'popular_label_en' => 'Popular',
        'popular_label_ar' => 'الأكثر طلباً',
        'assisted_label_en' => 'Full Assisted Filing',
        'assisted_label_ar' => 'تجهيز الملف بالكامل',
        'turnaround_label_en' => 'Turnaround:',
        'turnaround_label_ar' => 'مدة الإنجاز:',
        'validity_label_en' => 'Validity:',
        'validity_label_ar' => 'الصلاحية:',
        'fee_label_en' => 'Service Fee',
        'fee_label_ar' => 'رسوم الخدمة',
        'requirements_label_en' => 'Requirements',
        'requirements_label_ar' => 'المتطلبات',
        'apply_label_en' => 'Apply',
        'apply_label_ar' => 'قدم الآن',
        'checklist_label_en' => 'Checklist',
        'checklist_label_ar' => 'متطلبات التقديم',
        'inquiry_label_en' => 'Inquire via WhatsApp',
        'inquiry_label_ar' => 'تواصل مع مسؤول التأشيرات',
    ],
    'embassy' => [
        'badge_en' => 'Diplomatic Quarter Attestation',
        'badge_ar' => 'خدمات السفارات والتصديقات بالرياض',
        'heading_en' => 'Official Embassy &',
        'heading_ar' => 'تصديقات وزارة الخارجية و',
        'highlight_en' => 'Legal Attestation',
        'highlight_ar' => 'السفارات الأجنبية',
        'description_en' => 'Fast-track legalization and consular stamping for commercial, educational, and personal documents through MOFA and foreign embassies.',
        'description_ar' => 'إنهاء وتصديق كافة المعاملات والوثائق التجارية والأكاديمية والشخصية من وزارة الخارجية السعودية والسفارات بالحي الدبلوماسي بالرياض.',
        'tabs' => [
            ['id' => 'all', 'label_en' => 'All Services', 'label_ar' => 'جميع الخدمات'],
            ['id' => 'commercial', 'label_en' => '🏢 Commercial & MOFA', 'label_ar' => '🏢 الشركات والتجارة'],
            ['id' => 'educational', 'label_en' => '🎓 Educational Degrees', 'label_ar' => '🎓 الشهادات الأكاديمية'],
            ['id' => 'civil', 'label_en' => '👨‍👩‍👦 Civil & Family', 'label_ar' => '👨‍👩‍👦 الوثائق الشخصية'],
            ['id' => 'appointments', 'label_en' => '📅 Appointments', 'label_ar' => '📅 حجز المواعيد'],
        ],
        'included_label_en' => "What's Included:",
        'included_label_ar' => 'الإجراءات المشمولة:',
        'starting_label_en' => 'Starting From',
        'starting_label_ar' => 'الرسوم من',
        'cta_label_en' => 'Start Attestation',
        'cta_label_ar' => 'بدء التصديق',
        'items' => [
            [
                'id' => 'mofa-attestation', 'title_en' => 'MOFA & Foreign Embassy Attestation', 'title_ar' => 'تصديق وزارة الخارجية والسفارات الأجنبية', 'category' => 'commercial', 'tag_en' => 'Most Requested', 'tag_ar' => 'الأكثر طلباً', 'popular' => true, 'turnaround_en' => '2 - 3 Business Days', 'turnaround_ar' => '2 - 3 أيام عمل', 'price' => '250 SAR',
                'description_en' => 'Full authentication chain from Saudi Ministry of Foreign Affairs (MOFA) to international embassies in the Riyadh Diplomatic Quarter.', 'description_ar' => 'إنهاء كافة إجراءات التصديق من وزارة الخارجية السعودية والسفارات المعتمدة بالحي الدبلوماسي بالرياض.',
                'features_en' => ['Saudi MOFA Digital Attestation', 'Foreign Embassy Final Seal & Stamp', 'Document Verification & Courier Handover', 'Apostille Certificate for Hague Countries'],
                'features_ar' => ['التصديق الرقمي من وزارة الخارجية السعودية', 'الختم والتصديق القنصلي من السفارة المعنية', 'مراجعة وتدقيق المستندات والتسليم المباشر', 'شهادة الأبوستيل لدول اتفاقية لاهاي'],
            ],
            [
                'id' => 'degree-legalization', 'title_en' => 'Educational & Degree Legalization', 'title_ar' => 'تصديق الشهادات والمؤهلات الأكاديمية', 'category' => 'educational', 'tag_en' => 'Students & Employees', 'tag_ar' => 'للطلاب والعمل', 'popular' => false, 'turnaround_en' => '3 - 5 Business Days', 'turnaround_ar' => '3 - 5 أيام عمل', 'price' => '350 SAR',
                'description_en' => 'Official verification for Saudi & foreign university diplomas, academic transcripts, and professional board licenses.', 'description_ar' => 'تصديق رسمي للشهادات الجامعية وسجلات الدرجات ورخص الهيئات المهنية من الملحقيات والجهات المختصة.',
                'features_en' => ['Saudi Ministry of Education Stamping', 'Cultural Mission / Attache Clearance', 'Embassy Verification for Employment Visas', 'Certified True Copy Issuance'],
                'features_ar' => ['تصديق وزارة التعليم السعودية', 'موافقة وختم الملحقية الثقافية', 'تصديق السفارة لفيز العمل والإقامة', 'إصدار نسخ طبق الأصل المعتمدة'],
            ],
            [
                'id' => 'commercial-legalization', 'title_en' => 'Commercial & Corporate Legalization', 'title_ar' => 'تصديق العقود والوثائق التجارية', 'category' => 'commercial', 'tag_en' => 'Business & Trade', 'tag_ar' => 'للشركات والأعمال', 'popular' => true, 'turnaround_en' => '2 - 4 Business Days', 'turnaround_ar' => '2 - 4 أيام عمل', 'price' => '450 SAR',
                'description_en' => 'Authentication of commercial contracts, board resolutions, powers of attorney, and commercial registrations.', 'description_ar' => 'توثيق العقود التجارية، قرارات مجالس الإدارة، الوكالات الشرعية، والسجلات التجارية لدى الغرفة التجارية والخارجية.',
                'features_en' => ['Saudi Chamber of Commerce Legalization', 'Ministry of Commerce & MOFA Attestation', 'Target Country Embassy Stamping', 'Bilingual Arabic-English Verification'],
                'features_ar' => ['تصديق الغرفة التجارية السعودية', 'تصديق وزارة التجارة والخارجية', 'ختم سفارة الدولة المستهدفة', 'المطابقة والترجمة المعتمدة عربي-إنجليزي'],
            ],
            [
                'id' => 'civil-attestation', 'title_en' => 'Civil Records & Family Attestation', 'title_ar' => 'تصديق الأحوال المدنية والوثائق الشخصية', 'category' => 'civil', 'tag_en' => 'Family Visa Support', 'tag_ar' => 'للإقامة والزيارة', 'popular' => false, 'turnaround_en' => '1 - 2 Business Days', 'turnaround_ar' => '1 - 2 يوم عمل', 'price' => '200 SAR',
                'description_en' => 'Official stamping for birth certificates, marriage contracts, police clearance records, and family status books.', 'description_ar' => 'تصديق وتوثيق شهادات الميلاد، عقود الزواج، شهادات الخلو من السوابق، ودفاتر العائلة لدى السفارات.',
                'features_en' => ['Ministry of Interior / Police Clearance Seal', 'Saudi Ministry of Justice Endorsement', 'Embassy Stamping for Family Residency', 'Official Certified Translation Included'],
                'features_ar' => ['ختم الأدلة الجنائية / وزارة الداخلية', 'تصديق وزارة العدل السعودية', 'ختم السفارة لاستقدام العائلة والإقامة', 'ترجمة معتمدة رسمية مشمولة'],
            ],
            [
                'id' => 'embassy-appointments', 'title_en' => 'Embassy VIP Appointment Booking', 'title_ar' => 'حجز مواعيد السفارات ومراكز التأشيرات', 'category' => 'appointments', 'tag_en' => 'Express Slots', 'tag_ar' => 'مواعيد سريعة', 'popular' => false, 'turnaround_en' => 'Same-Day Booking', 'turnaround_ar' => 'حجز فوري نفس اليوم', 'price' => '150 SAR',
                'description_en' => 'Fast-track appointment scheduling for VFS Global, TLScontact, BLS, and direct consular interview slots across Riyadh.', 'description_ar' => 'حجز أسرع المواعيد المتاحة لدى VFS Global وTLScontact وBLS ومواعيد المقابلات المباشرة بالسفارات.',
                'features_en' => ['Prime Time & Early Slot Availability', 'Document Checklist & Form Pre-Check', 'SMS & Email Slot Confirmation Alert', 'Embassy Submission VIP Support'],
                'features_ar' => ['إتاحة المواعيد المميزة والصباحية المبكرة', 'التدقيق المسبق لملف واستمارة التقديم', 'إشعار وتأكيد الموعد عبر الجوال والإيميل', 'توجيهات المقابلة والتقديم لدى المركز'],
            ],
        ],
    ],
    'translation' => [
        'badge_en' => 'Official Certified Translation', 'badge_ar' => 'الترجمة المعتمدة لجميع السفارات',
        'heading_en' => 'Accredited Legal Translation for', 'heading_ar' => 'ترجمة معتمدة مقبولة لدى',
        'highlight_en' => 'Embassies & Ministries', 'highlight_ar' => 'كافة السفارات والجهات',
        'description_en' => '100% accepted by all foreign embassies in Riyadh, VFS Global, TLScontact, and Saudi ministries. Fast and sworn.',
        'description_ar' => 'معتمدة لدى جميع السفارات الأجنبية بالرياض ومراكز VFS Global وTLScontact والوزارات السعودية. دقة لغوية مع أختام رسمية معتمدة.',
        'popular_label_en' => 'Popular', 'popular_label_ar' => 'الأكثر طلباً',
        'turnaround_label_en' => 'Turnaround:', 'turnaround_label_ar' => 'سرعة الإنجاز:',
        'advantages' => [
            ['icon' => 'stamp', 'title_en' => 'Embassy-Approved Seal', 'title_ar' => 'ختم معتمد لدى السفارات', 'description_en' => 'Recognized by Schengen, UK, US, and Asian missions.', 'description_ar' => 'مقبولة لدى سفارات دول الشنغن، بريطانيا، وأمريكا وكندا.'],
            ['icon' => 'clock', 'title_en' => 'Same-Day Fast Delivery', 'title_ar' => 'تسليم فوري نفس اليوم', 'description_en' => 'Urgent documents translated and sealed in 2 to 4 hours.', 'description_ar' => 'تسليم الوثائق العاجلة بصيغة PDF ومطبوعة خلال 2 إلى 4 ساعات.'],
            ['icon' => 'shield', 'title_en' => '100% Legal Accuracy', 'title_ar' => 'دقة ومطابقة قانونية 100%', 'description_en' => 'Conducted by certified sworn translators ensuring precision.', 'description_ar' => 'مترجمون محلفون معتمدون لضمان صحة المصطلحات وسرية البيانات.'],
        ],
        'document_types' => [
            ['id' => 'travel-visa', 'title_en' => 'Visa & Travel Documents', 'title_ar' => 'وثائق السفر واستخراج التأشيرات', 'popular' => true, 'turnaround_en' => 'Same-Day (2 - 4 Hours)', 'turnaround_ar' => 'نفس اليوم (2 - 4 ساعات)', 'items_en' => ['Salary & HR Employment Certificates', 'Bank Statements & Financial Proofs', 'Saudi National ID & Iqama Cards', 'Travel Insurance & Hotel Vouchers'], 'items_ar' => ['خطابات التعريف بالراتب والموارد البشرية', 'كشوف الحسابات البنكية والإثباتات المالية', 'بطاقات الهوية الوطنية والإقامة السعودية', 'وثائق التأمين الطبي وتأكيدات الفنادق']],
            ['id' => 'personal-civil', 'title_en' => 'Civil & Personal Records', 'title_ar' => 'الوثائق الشخصية والأحوال المدنية', 'popular' => false, 'turnaround_en' => '24 Hours Express', 'turnaround_ar' => '24 ساعة إنجاز سريع', 'items_en' => ['Birth & Marriage Certificates', 'Family Cards & Identification Books', 'Police Clearance / Good Conduct', 'Driver’s Licenses & International Permits'], 'items_ar' => ['شهادات الميلاد وعقود الزواج الرسمية', 'بطاقات العائلة ودفاتر النفوس', 'شهادات الخلو من السوابق الجنائية', 'رخص القيادة والتصاريح الدولية']],
            ['id' => 'academic-commercial', 'title_en' => 'Academic & Commercial Papers', 'title_ar' => 'الشهادات والوثائق التجارية', 'popular' => false, 'turnaround_en' => '24 - 48 Hours', 'turnaround_ar' => '24 - 48 ساعة', 'items_en' => ['University Degrees & Academic Transcripts', 'Commercial Registrations (CR)', 'Articles of Association & Memorandums', 'Medical Reports & Health Certificates'], 'items_ar' => ['الشهادات الجامعية وسجلات الدرجات', 'السجلات التجارية والوكالات والقرارات', 'عقود التأسيس والاتفاقيات الدولية', 'التقارير والشهادات الطبية الرسمية']],
        ],
        'quote_badge_en' => 'Instant Translation Quote', 'quote_badge_ar' => 'تسعير وترجمة فورية',
        'quote_title_en' => 'Upload & Translate Today', 'quote_title_ar' => 'أرسل وثيقتك للترجمة الآن',
        'quote_description_en' => 'Send a photo or PDF directly to our translation desk on WhatsApp.', 'quote_description_ar' => 'أرسل صورة أو ملف PDF مباشرة عبر الواتساب للحصول على السعر والوقت.',
        'document_label_en' => 'Select Document Category:', 'document_label_ar' => 'نوع الوثيقة:',
        'language_label_en' => 'Target Language:', 'language_label_ar' => 'اللغة المطلوب الترجمة إليها:',
        'upload_title_en' => 'Snap photo or attach PDF via WhatsApp', 'upload_title_ar' => 'التقط صورة واضحة أو أرفق ملف PDF عبر الواتساب',
        'upload_description_en' => 'Our translation desk responds in under 15 minutes.', 'upload_description_ar' => 'يرد فريق الترجمة خلال أقل من 15 دقيقة.',
        'cta_label_en' => 'Send Document via WhatsApp', 'cta_label_ar' => 'إرسال المستند عبر الواتساب',
        'document_options' => [
            ['value' => 'Visa & Employment Papers', 'label_en' => 'Visa & Employment Papers', 'label_ar' => 'خطابات التعريف بالراتب وكشوف الحساب'],
            ['value' => 'National ID / Iqama', 'label_en' => 'National ID / Iqama / Family Card', 'label_ar' => 'بطاقات الهوية والإقامة ودفتر العائلة'],
            ['value' => 'Marriage / Birth Certificate', 'label_en' => 'Marriage / Birth Certificate', 'label_ar' => 'عقود الزواج وشهادات الميلاد'],
            ['value' => 'Commercial Registration / Contracts', 'label_en' => 'Commercial Registration / Legal Contracts', 'label_ar' => 'السجلات التجارية والعقود القانونية'],
            ['value' => 'University Degree', 'label_en' => 'University Degree & Transcripts', 'label_ar' => 'الشهادات الجامعية والمؤهلات الدراسية'],
        ],
        'languages' => [
            ['value' => 'English', 'label_en' => 'English', 'label_ar' => 'الإنجليزية'], ['value' => 'French', 'label_en' => 'French', 'label_ar' => 'الفرنسية'], ['value' => 'German', 'label_en' => 'German', 'label_ar' => 'الألمانية'], ['value' => 'Spanish', 'label_en' => 'Spanish', 'label_ar' => 'الإسبانية'], ['value' => 'Italian', 'label_en' => 'Italian', 'label_ar' => 'الإيطالية'], ['value' => 'Turkish', 'label_en' => 'Turkish', 'label_ar' => 'التركية'], ['value' => 'Russian', 'label_en' => 'Russian', 'label_ar' => 'الروسية'], ['value' => 'Chinese', 'label_en' => 'Chinese', 'label_ar' => 'الصينية'],
        ],
    ],
    'license' => [
        'badge_en' => 'Official UN International Permit', 'badge_ar' => 'رخصة القيادة الدولية المعتمدة',
        'heading_en' => 'International', 'heading_ar' => 'استخراج رخصة القيادة',
        'highlight_en' => 'Driving License', 'highlight_ar' => 'الدولية الفورية',
        'description_en' => 'Drive legally across 150+ countries. Issued in accordance with UN conventions, accepted by all major car rental agencies.',
        'description_ar' => 'قد سيارتك بكل أمان وقانونية في أكثر من 150 دولة حول العالم. تصدر وفقاً لاتفاقيات الأمم المتحدة ومعتمدة لدى كافة شركات تأجير السيارات العالمية.',
        'popular_label_en' => 'Most Popular Choice', 'popular_label_ar' => 'الخيار الأكثر طلباً',
        'turnaround_label_en' => 'Turnaround:', 'turnaround_label_ar' => 'سرعة الإنجاز:',
        'fee_label_en' => 'Total Issuance Fee', 'fee_label_ar' => 'رسوم الإصدار شاملة',
        'fee_suffix_en' => '/ all-inclusive', 'fee_suffix_ar' => '/ شامل الدفتر',
        'features_label_en' => 'Permit Specifications:', 'features_label_ar' => 'المواصفات والاعتمادات:',
        'cta_label_en' => 'Apply for this Permit', 'cta_label_ar' => 'طلب إصدار الرخصة',
        'plans' => [
            ['id' => 'one-year', 'title_en' => '1-Year International Permit', 'title_ar' => 'رخصة القيادة الدولية - سنة واحدة', 'price' => '180 SAR', 'turnaround_en' => '15 - 30 Minutes (Express)', 'turnaround_ar' => '15 - 30 دقيقة (فوري)', 'popular' => false, 'recommended_en' => 'Short holidays & tourist vacations', 'recommended_ar' => 'للإجازات القصيرة والسياحة', 'features_en' => ['Accepted in 150+ Countries Worldwide', 'Compliant with 1949 UN Geneva Convention', 'Immediate Digital Copy + Hard Booklet', 'Official 10-Language Translation', 'Car Rental Insurance Acceptance Guaranteed'], 'features_ar' => ['معتمدة في أكثر من 150 دولة حول العالم', 'متوافقة مع اتفاقية جنيف للأمم المتحدة 1949', 'دفتر رسمي معتمد + نسخة إلكترونية فورية', 'مترجمة رسمياً إلى 10 لغات عالمية', 'قبول مضمون لدى كافة شركات تأجير السيارات']],
            ['id' => 'two-year', 'title_en' => '2-Year International Permit', 'title_ar' => 'رخصة القيادة الدولية - سنتان', 'price' => '280 SAR', 'turnaround_en' => '15 - 30 Minutes (Express)', 'turnaround_ar' => '15 - 30 دقيقة (فوري)', 'popular' => true, 'recommended_en' => 'Frequent business travelers & expats', 'recommended_ar' => 'الخيار الأكثر توفيراً للمسافرين', 'features_en' => ['Best Value & Long-Term Savings', 'Accepted in 150+ Countries Worldwide', 'Compliant with 1949 & 1968 Conventions', 'Immediate Digital Copy + Hard Booklet', 'Free Re-Issuance if Damaged Abroad'], 'features_ar' => ['أفضل قيمة وأعلى توفير للمسافرين الدائمين', 'معتمدة في أكثر من 150 دولة حول العالم', 'متوافقة مع اتفاقيتي 1949 و1968 الدولية', 'دفتر رسمي معتمد + نسخة إلكترونية فورية', 'إعادة إصدار مجانية في حال التلف أثناء السفر']],
            ['id' => 'three-year', 'title_en' => '3-Year International Permit', 'title_ar' => 'رخصة القيادة الدولية - 3 سنوات', 'price' => '380 SAR', 'turnaround_en' => '15 - 30 Minutes (Express)', 'turnaround_ar' => '15 - 30 دقيقة (فوري)', 'popular' => false, 'recommended_en' => 'Overseas students & frequent flyers', 'recommended_ar' => 'للطلاب والمبتعثين ورجال الأعمال', 'features_en' => ['Maximum Legal Driving Validity', 'Accepted in Europe, USA, UK, Asia, & Gulf', 'No Annual Renewal Required', 'Immediate Digital Copy + Hard Booklet', 'VIP Dedicated Support Hotline'], 'features_ar' => ['أطول مدة صلاحية قانونية لقيادة السيارات', 'معتمدة في أوروبا وأمريكا وبريطانيا وآسيا', 'لا حاجة للتجديد السنوي المتكرر', 'دفتر رسمي معتمد + نسخة إلكترونية فورية', 'دعم استشاري مخصص على مدار الساعة']],
        ],
    ],
];
